# Generated by Django 4.2.4 on 2023-08-31 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo del Posteo')),
                ('content', models.TextField(blank=True, max_length=256, null=True, verbose_name='Contenido del Posteo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion del Post')),
                ('tzone', models.CharField(choices=[('EU', 'EUROPE'), ('AS', 'ASIA'), ('US', 'UNITED STATES')], max_length=10, verbose_name='Zona Horaria')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author del Posteo')),
            ],
        ),
    ]
