# Generated by Django 4.2.4 on 2023-09-01 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_post_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='etiqueta_tarea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tareas.etiqueta'),
        ),
    ]
