# Generated by Django 4.2.4 on 2023-09-02 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_post_etiqueta_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fecha_limite',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 13, 19, 2, 667739, tzinfo=datetime.timezone.utc), verbose_name='Fecha Limite del Post'),
            preserve_default=False,
        ),
    ]
