# Generated by Django 4.2.4 on 2023-09-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20, verbose_name='Nombre de Prioridad')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color')),
            ],
        ),
    ]
