# Generated by Django 4.2.4 on 2023-09-05 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.prioridad', verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='prioridad',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre de Prioridad'),
        ),
    ]
